-- Отключаем проверку внешних ключей для безопасного удаления таблиц
SET
REFERENTIAL_INTEGRITY FALSE;

-- Удаление таблиц в ПРАВИЛЬНОМ порядке (сначала зависимые, затем родительские)
DROP TABLE IF EXISTS review_likes;
DROP TABLE IF EXISTS reviews;
DROP TABLE IF EXISTS feed_events;
DROP TABLE IF EXISTS film_director;
DROP TABLE IF EXISTS likes;
DROP TABLE IF EXISTS film_genres;
DROP TABLE IF EXISTS friendships;
DROP TABLE IF EXISTS films;
DROP TABLE IF EXISTS users;
DROP TABLE IF EXISTS director;
DROP TABLE IF EXISTS genres;
DROP TABLE IF EXISTS mpa_ratings;

-- Включаем проверку внешних ключей обратно
SET
REFERENTIAL_INTEGRITY TRUE;

-- Создание таблиц в правильном порядке (сначала родительские, затем зависимые)

-- 1. Базовые независимые таблицы
CREATE TABLE IF NOT EXISTS mpa_ratings
(
    id          INTEGER PRIMARY KEY,
    name        VARCHAR(10) NOT NULL,
    description VARCHAR(255)
    );

CREATE TABLE IF NOT EXISTS genres
(
    id   INTEGER PRIMARY KEY,
    name VARCHAR(50) NOT NULL
    );

CREATE TABLE IF NOT EXISTS director
(
    id
    INTEGER
    GENERATED
    BY
    DEFAULT AS
    IDENTITY
    PRIMARY
    KEY,
    name
    VARCHAR
(
    255
) NOT NULL UNIQUE
    );

CREATE TABLE IF NOT EXISTS users
(
    id
    INTEGER
    GENERATED
    BY
    DEFAULT AS
    IDENTITY
    PRIMARY
    KEY,
    email
    VARCHAR
(
    255
) NOT NULL UNIQUE,
    login VARCHAR
(
    50
) NOT NULL UNIQUE,
    name VARCHAR
(
    255
),
    birthday DATE NOT NULL
    );

-- 2. Таблица films (зависит от mpa_ratings)
CREATE TABLE IF NOT EXISTS films
(
    id           INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name         VARCHAR(255) NOT NULL,
    description  VARCHAR(200),
    release_date DATE         NOT NULL,
    duration     INTEGER      NOT NULL,
    mpa_id       INTEGER      REFERENCES mpa_ratings (id) ON DELETE SET NULL
    );

-- 3. Таблицы связей (зависят от films, users, genres, director)
CREATE TABLE IF NOT EXISTS film_genres
(
    film_id  INTEGER REFERENCES films (id) ON DELETE CASCADE,
    genre_id INTEGER REFERENCES genres (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, genre_id)
    );

CREATE TABLE IF NOT EXISTS likes
(
    film_id INTEGER REFERENCES films (id) ON DELETE CASCADE,
    user_id INTEGER REFERENCES users (id) ON DELETE CASCADE,
    PRIMARY KEY (film_id, user_id)
    );

CREATE TABLE IF NOT EXISTS friendships
(
    user_id    INTEGER NOT NULL,
    friend_id  INTEGER NOT NULL,
    status     VARCHAR(20) DEFAULT 'PENDING',
    created_at TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (user_id, friend_id),
    FOREIGN KEY (user_id) REFERENCES users (id) ON DELETE CASCADE,
    FOREIGN KEY (friend_id) REFERENCES users (id) ON DELETE CASCADE
    );

CREATE TABLE IF NOT EXISTS film_director
(
    film_id     INTEGER REFERENCES films (id) ON UPDATE CASCADE ON DELETE CASCADE,
    director_id INTEGER REFERENCES director (id) ON UPDATE CASCADE ON DELETE CASCADE,
    PRIMARY KEY (film_id, director_id)
    );

-- 4. Таблицы для отзывов (зависят от films и users)
CREATE TABLE IF NOT EXISTS reviews (
                                       id
                                       INTEGER
                                       GENERATED
                                       BY
                                       DEFAULT AS
                                       IDENTITY
                                       PRIMARY
                                       KEY,
                                       content
                                       TEXT
                                       NOT
                                       NULL,
                                       is_positive
                                       BOOLEAN
                                       NOT
                                       NULL,
                                       user_id
                                       INTEGER
                                       NOT
                                       NULL
                                       REFERENCES
                                       users
(
                                       id
) ON DELETE CASCADE,
    film_id INTEGER NOT NULL REFERENCES films(id) ON DELETE CASCADE,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
    );

CREATE TABLE IF NOT EXISTS review_likes (
                                            review_id
                                            INTEGER
                                            NOT
                                            NULL
                                            REFERENCES
                                            reviews
(
                                            id
) ON DELETE CASCADE,
    user_id INTEGER NOT NULL REFERENCES users(id) ON DELETE CASCADE,
    is_like BOOLEAN NOT NULL,
    PRIMARY KEY (review_id, user_id)
    );

-- 5. Таблица для ленты событий (зависит от users)
CREATE TABLE IF NOT EXISTS feed_events (
                                           event_id
                                           INTEGER
                                           GENERATED
                                           BY
                                           DEFAULT AS
                                           IDENTITY
                                           PRIMARY
                                           KEY,
                                           user_id
                                           INTEGER
                                           NOT
                                           NULL
                                           REFERENCES
                                           users
(
                                           id
) ON DELETE CASCADE,
    entity_id INTEGER NOT NULL,
    event_type VARCHAR(10) NOT NULL CHECK (event_type IN ('LIKE', 'REVIEW', 'FRIEND')),
    operation VARCHAR(10) NOT NULL CHECK (operation IN ('ADD', 'REMOVE', 'UPDATE')),
    timestamp BIGINT NOT NULL,
    -- Для оптимизации поиска событий пользователя
    UNIQUE(user_id, event_id)
    );

-- Сброс sequence для автоинкремента (ВАЖНО для тестов!)
ALTER TABLE director
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE users
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE films
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE reviews
    ALTER COLUMN id RESTART WITH 1;
ALTER TABLE feed_events
    ALTER COLUMN event_id RESTART WITH 1;

-- Индексы для оптимизации запросов (оставлены без изменений)
CREATE INDEX IF NOT EXISTS idx_films_mpa ON films (mpa_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_film ON film_genres (film_id);
CREATE INDEX IF NOT EXISTS idx_film_genres_genre ON film_genres (genre_id);
CREATE INDEX IF NOT EXISTS idx_likes_film ON likes (film_id);
CREATE INDEX IF NOT EXISTS idx_likes_user ON likes (user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_user ON friendships (user_id);
CREATE INDEX IF NOT EXISTS idx_friendships_friend ON friendships (friend_id);
CREATE INDEX IF NOT EXISTS idx_reviews_film ON reviews(film_id);
CREATE INDEX IF NOT EXISTS idx_reviews_user ON reviews(user_id);
CREATE INDEX IF NOT EXISTS idx_review_likes_review ON review_likes(review_id);
CREATE INDEX IF NOT EXISTS idx_review_likes_user ON review_likes(user_id);
CREATE INDEX IF NOT EXISTS idx_reviews_created ON reviews(created_at);
CREATE INDEX IF NOT EXISTS idx_feed_events_user ON feed_events(user_id);
CREATE INDEX IF NOT EXISTS idx_feed_events_user_timestamp ON feed_events(user_id, timestamp DESC);
CREATE INDEX IF NOT EXISTS idx_feed_events_timestamp ON feed_events(timestamp DESC);